<REQUEST id='messagesend' comment=''>
	  <VERSION>1.0</VERSION>
	  <MSGID>${MSGID}</MSGID>
	  <MSGTYPE>${MSGTYPE}</MSGTYPE>
	  <TEMPID>${TEMPID}</TEMPID>
	  <PRIORITY>${PRIORITY}</PRIORITY>
	  <RECEIVER>${RECEIVER}</RECEIVER>
	  <TITLE>${TITLE}</TITLE>
	  <FILENAME>${FILENAME}</FILENAME>
	  <FILE>${FILE}</FILE>
	  <NSRSBH>${NSRSBH}</NSRSBH>
	  <DEVICETYPE>${DEVICETYPE}</DEVICETYPE>
	<VALUES>
	 	<#list VALUES as p>
			<VALUE>${p}</VALUE >
		</#list>
	</VALUES>
</REQUEST>
